language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm # ignore errors, see below

# lock distro so new future defaults will not break the build
dist: xenial

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
  allow_failures:
    - php: hhvm

sudo: false

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
